#language: pt

Funcionalidade: Popular painel

Cenario: Cadastrar Vídeos

	Dado que eu acesse o painel drupal
	Então deveria cadastrar os vídeos no drupal
| titulo | idioma | segmento | categoria | imagem | link | data |
| Natura + Moda + Casa: Conheça mais sobre esta linha especial de produtos que enchem os olhos! | Português, Brasil | 4 | Mais dicas para trabalhar em favor do seu negócio. | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/116150733 | jan 07 2015 |
| Utilizando o e-mail para vendas: Utilize o e-mail para divulgar seu Espaço, manter contato com seus clientes e apresentar oportunidades comerciais. | Português, Brasil | 4 | Mais dicas para trabalhar em favor do seu negócio. | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/116151061 | jan 07 2015 |
| Dicas de maquiagem pelo Facebook: Oferecer dicas de maquiagem é uma excelente maneira de convidar as pessoas a conhecer o seu Espaço e demonstrar o uso dos produtos! | Português, Brasil | 4 | Mais dicas para trabalhar em favor do seu negócio. | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/116151059 | jan 07 2015 |
| Usando o Youtube para vendas: Um ótimo veículo para demonstração de produtos. | Português, Brasil | 4 | Mais dicas para trabalhar em favor do seu negócio. | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/116151485 | jan 07 2015 |
| Usando o Hangout para vendas: Mais uma maneira de entrar em contato com seus contatos e clientes para divulgar seu Espaço, apresentar oportunidades comerciais e demonstrar produtos. | Português, Brasil | 4 | Mais dicas para trabalhar em favor do seu negócio. | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/116151777 | jan 07 2015 |
| Seus e-mails estão chegando até seus clientes? Dicas para evitar que seus e-mails de divulgação caiam na caixa de SPAM de seus contatos.  | Português, Brasil | 4 | Mais dicas para trabalhar em favor do seu negócio. | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/116151780 | jan 07 2015 |
| Batom Matte de Natura Faces: Conheça os diferenciais do batom Matte de Natura Faces. | Português, Brasil | 4 | Produtos: conheça seu portfólio! | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/90121457 | mar 26 2014 |
| Dicas sobre a linha Chronos: Aprenda a orientar seus clientes sobre os produtos da linha Chronos!  | Português, Brasil | 4 | Produtos: conheça seu portfólio! | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/90121850 | mai 05 2014 |
| Como combinar sombras: Aprenda a combinar sombras com Marcos Costa.  | Português, Brasil | 4 | Produtos: conheça seu portfólio! | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/94014556 | jan 07 2015 |
| Linha Plant Cachos Marcantes: 5 dicas que você precisa saber para lucrar mais com a linha Plant Cachos Marcantes!  | Português, Brasil | 4 | Produtos: conheça seu portfólio! | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/123775032 | mar 31 2015 |
| Presentes: 4 motivos para trabalhar presentes na sua estratégia de vendas.  | Português, Brasil | 4 | Produtos: conheça seu portfólio! | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/123799617 | mar 31 2015 |
| Tem Lançamento na Rede Natura: Kaiak Expedição; Sève cereja e amêndoas; Águas Banho de Chuva e Banho de Mar; Base Una Multi Benefício.  | Português, Brasil | 4 | Produtos: conheça seu portfólio! | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/131779567 | jun 25 2015 |
| Tem Lançamento na Rede Natura: Tododia Macadâmia Marcante e Algodão Envolvente; Novas sombras Aquarela; Batom Balm Aquarela.  | Português, Brasil | 4 | Produtos: conheça seu portfólio! | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/132820222 | jul 07 2015 |
| Como Vender Maquiagem: Preparação da pele e os diferentes tipos de base.  | Português, Brasil | 4 | Produtos: conheça seu portfólio! | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/135413845 | ago 04 2015 |
| Encantar seus clientes e gerar novas vendas: Um bom relacionamento com seus clientes é a chave para negócios duradouros. | Português, Brasil | 4 | Simplificando o Marketing Digital | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/109808678 | out 23 2014 |
| Gerar vendas: Dicas para realizar as primeiras vendas em seu Espaço. | Português, Brasil | 4 | Simplificando o Marketing Digital | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/109808676 | out 23 2014 |
| Blog: O primeiro passo para conquistar clientes e realizar vendas é convidar pessoas para conhecer o seu Espaço. Confira como usar conteúdos interessantes como uma forma de levar pessoas até o seu Espaço! | Português, Brasil | 4 | Simplificando o Marketing Digital | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/109805596 | out 23 2014 |
| Email: O primeiro passo para conquistar clientes e realizar vendas é convidar pessoas para conhecer o seu Espaço. Confira como utilizar o e-mail para isto. | Português, Brasil | 4 | Simplificando o Marketing Digital | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/109805595 | out 23 2014 |
| Facebook: O primeiro passo para conquistar clientes e realizar vendas é convidar pessoas para conhecer o seu Espaço. Veja como o Facebook pode ser útil para isto.  | Português, Brasil | 4 | Simplificando o Marketing Digital | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/109805592 | out 23 2014 |
| Atrair visitantes: O primeiro passo para conquistar clientes e realizar vendas é convidar pessoas para conhecer o seu Espaço. Aqui você encontra caminhos para começar! | Português, Brasil | 4 | Simplificando o Marketing Digital | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/109805590 | out 23 2014 |
| Relações e Negócios Digitais: O momento atual favorece o crescimento de Negócios como o seu! | Português, Brasil | 4 | Simplificando o Marketing Digital | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/109805589 | out 23 2014 |
| Vídeo Aula: Como segmentar sua base de contatos para gerar mais vendas.  | Português, Brasil | 4 | Simplificando o Marketing Digital | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/130562519 | jun 12 2015 |
| Como investir seu TEMPO? Confira a videoaula - Tempo: um investimento FUNDAMENTAL para o desenvolvimento dos seus negócios.  | Português, Brasil | 4 | Simplificando o Marketing Digital | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/127262527 | mai 08 2015 |
| Vídeo Aula: Você trabalha apenas divulgação? Veja quais são os papéis para ser um Consultor Digital de sucesso! | Português, Brasil | 4 | Simplificando o Marketing Digital | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/136514132 | jul 10 2015 |
| Vídeo Aula: Como falar da maneira certa com cada tipo de contato. | Português, Brasil | 4 | Simplificando o Marketing Digital | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/133171832 | jul 10 2015 |
| Vídeo Aula: Qual a melhor forma de falar com clientes que você conhece e que você não conhece pessoalmente para gerar mais vendas.  | Português, Brasil | 4 | Simplificando o Marketing Digital | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/134194122 | jul 22 2015 |
| Vídeo Aula: Como reinvestir seus lucros para gerar melhores resultados. | Português, Brasil | 4 | Simplificando o Marketing Digital | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/136622444 | ago 18 2015 |
| A Rede Natura: Você decidiu se engajar na atividade de Consultoria Natura Digital. E agora, por onde começar? Confira as nossas dicas nos conteúdos disponíveis abaixo! | Português, Brasil | 4 | A Rede Natura | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/109958065 | out 24 2014 |
| Novo Painel de Negócios: Explore seu novo Painel | Português, Brasil | 4 | A Rede Natura | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/122347986 | mar 16 2015 |
| Enviar E-mails: Una excelente forma de comunicarte con tus clientes sin invadir su espacio personal es a través de e mails. En este formato, puedes crear comunicaciones personalizas e indicarle a tus clientes que conoces sus gustos y preferencias. Felicitarlos por fechas conmemorativas y mucho más… te invitamos a generar tus modelos y a difundir tu espacio en Red Natura! | Portuguese, Chile | 4 | A Rede Natura | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/136131507 | ago 12 2015 |
| Atraer Visitantes: No sólo se trata de vender, sino de encantar a tus clientes con novedades y un acompañamiento diferenciado. Es importante dar a conocer tu espacio de formas simples y económicas y generar redes a través de amigos y familiares. ¿Quieres aprender más? Te invitamos a revisar nuestros videos y hacerte una consultora digital experta. | Portuguese, Chile | 4 | A Rede Natura | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/136128240 | ago 12 2015 |
| Red Natura: Tu Panel de Negocios. | Portuguese, Chile | 4 | A Rede Natura | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/136135086 | ago 12 2015 |
| Bienvenida a Red Natura: Queremos que desarrolles tus habilidades por completo. Negocios, Relaciones y disemines el Bien Estar Bien. Te invitamos a conocer un poco más de Red Natura, la extensión del relacionamiento del mundo presencial y ventas por internet. | Portuguese, Chile | 4 | A Rede Natura | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/136135085 | ago 12 2015 |
| Como encantar a tus Clientes: Lo más importante es el encantamiento, la red de relaciones y la diseminación del Bien Estar Bien. En este video, queremos ayudarte a saber cuál es el mejor momento para enviar información, como abordar a tus clientes nuevos y a los más antiguos, como personalizar tus comunicaciones y mucho más. Te invitamos a conocer más y nuevos tips para ti! | Portuguese, Chile | 4 | A Rede Natura | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/136128241 | ago 12 2015 |
| Facebook: Aprovecha la red social más grande que existe en estos momentos para difundir, comunicar y emprender. Solo debes seguir los tips que te entregamos, y cada día serás un usuario más experto. Conoce cómo publicitar tu espacio y generar más y mejores ventas! | Portuguese, Chile | 4 | A Rede Natura | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/136131509 | ago 12 2015 |
| ¿Como Generar Ventas?: Lo más importante es conocer sobre tus tareas y actividades diarias. Genera un orden de clientes, sus gustos y compras frecuentes para ofrecer las mejores opciones, de ésta forma siempre serán bienvenidos tus comentarios y la comunicación será cada vez más fluida entre tú y tus clientes. | Portuguese, Chile | 4 | A Rede Natura | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/136135083 | ago 12 2015 |
| Relaciones de Negocios Digitales: ¿Se pueden hacer negocios a través de redes sociales? Claro que sí, y Red Natura te explica cómo. Encanta y fideliza a tus clientes. Crea tu red de contactos y aprende a cómo manejar tu canal. | Portuguese, Chile | 4 | A Rede Natura | SUZUKI_Swift_SHORTArticles_2013_FEB_natura_04.jpg | https://vimeo.com/136135087 | ago 12 2015 |